routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['register'=>false, 'reset'=>false]);

Route::group(['middleware' => ['auth']], function () {
    Route::resource('/agendamentos', 'AgendamentoController');
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('/pets', 'PetController');
    Route::resource('/servicos', 'ServicoController');
    
    Route::prefix('relatorios')->group(function(){
        Route::get('/avaliacoes', 'RelatorioAvaliacoesController@index')->name('relatorio_avaliacoes');
    });
    
    
});

app/Models/Servico.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Servico extends Model
{
    
    protected $table = 'servicos';

    protected $primaryKey = 'id_produto_servico';

    public $incrementing = false;

    protected $with = ['produtoServico'];

    protected $fillable = [
        'tempo_estimado',
        'pontos_ganhos',
        'pontos_necessarios',
        'id_perfil',
        'id_unidade_tempo'
    ];

    public function getIdAttribute()
    {
        return $this->id_produto_servico;
    }

    public function getNomeAttribute()
    {
        return $this->produtoServico->nome;
    }

    public function getPrecoAttribute()
    {
        $preco = Preco::where('id_produto_servico', $this->id)
            ->where('ativo', 1)
            ->orderBy('id', 'desc')
            ->first();

        if ($preco) {
            return $preco->preco;
        } else {
            return '0,00';
        }
    }

    /**
     * Carrega automaticamente o relacionamento com produtos_servicos
     */
    public function produtoServico()
    {
        return $this->belongsTo('App\Models\ProdutoServico', 'id_produto_servico', 'id');
    }

    /**
     * Faz o JOIN, quando manualmente chamado, com a tabela de produtos_servicos para facilitar a filtragem e ordenação de dados para listagem
     */
    public function scopeProdutoServico()
    {
        return $this->join('produtos_servicos', 'servicos.id_produto_servico', 'produtos_servicos.id');
    }

    public function perfil()
    {
        return $this->belongsTo('App\Models\Perfil', 'id_perfil', 'id');
    }

    public function unidadeTempo()
    {
        return $this->belongsTo('App\Models\UnidadeTempo', 'id_unidade_tempo', 'id');
    }

    public function scopeComNome($query, $nome)
    {
        return $query->where('nome', 'like', "%$nome%");
    }

    public function scopeAtivo($query)
    {
        return $query->whereHas('produtoServico', function ($q) {
            $q->where('ativo', 1);
        });
    }
}

app/Models/UnidadeTempo.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class UnidadeTempo extends Model
{
    protected $table = 'unidades_tempo';

    public function getSiglaAttribute()
    {
        if ($this->nome == 'Horas') {
            return 'h';
        } else if ($this->nome == 'Minutos') {
            return 'm';
        }

    }
}

app/Http/Controllers/ServicoController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\ServicoRequest;
use App\Models\Servico;
use App\Repositories\ServicoRepository;
use Exception;
use Illuminate\Cache\RetrievesMultipleKeys;
use Illuminate\Database\Eloquent\ModelNotFoundException;
use Illuminate\Http\Request;
use Illuminate\Routing\Route;
use Illuminate\Support\Facades\Session;

class ServicoController extends Controller
{

    public function __construct()
    {
        $this->repository = new ServicoRepository();
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {

        try {
            $this->authorize('viewAny', Servico::class);
            return $this->repository->index($request);
        } catch (\Exception $e) {
            Session::flash('message', ['type' => 'danger', 'message' => "Permissão negada"]);
            return redirect()->back();
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        try {
            $this->authorize('create', Servico::class);
            return $this->repository->create();
        } catch (\Exception $e) {
            Session::flash('message', ['type' => 'danger', 'message' => "Permissão negada"]);
            return redirect()->back();
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\ServicoRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ServicoRequest $request)
    {
        try {
            $this->authorize('create', Servico::class);
            $this->repository->store($request);
            return redirect()->route('servicos.index');
        } catch (\Exception $e) {
            Session::flash('message', ['type' => 'danger', 'message' => "Permissão negada"]);
            return redirect()->back();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    { }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        try {
            $this->authorize('view', [Servico::find($id), request()->user()]);
        } catch (\Exception $e) {
            Session::flash('message', ['type' => 'danger', 'message' => "Permissão negada"]);
            return redirect()->back();
        }

        try {
            $servico = Servico::findOrFail($id);
        } catch (ModelNotFoundException $e) {
            Session::flash('message', ['type' => 'danger', 'message' => "Serviço não encontrado."]);
            return redirect()->route('servicos.index');
        }
        return $this->repository->edit($id);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(ServicoRequest $request, $id)
    {
        try {
            $this->authorize('update', [Servico::find($id), $request->user()]);
        } catch (\Exception $e) {
            Session::flash('message', ['type' => 'danger', 'message' => "Permissão negada"]);
            return redirect()->back();
        }

        try {
            $servico = Servico::findOrFail($id);
        } catch (\Exception $e) {
            Session::flash('message', ['type' => 'danger', 'message' => "Serviço não encontrado."]);
            return redirect()->route('servicos.index');
        }

        $this->repository->update($request, $servico);
        return redirect()->route('servicos.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            $this->authorize('delete', [Servico::find($id), request()->user()]);
        } catch (\Exception $e) {
            Session::flash('message', ['type' => 'danger', 'message' => "Permissão negada"]);
        }

        try {
            $servico = Servico::findOrFail($id);
        } catch (\Exception $e) {
            Session::flash('message', ['type' => 'danger', 'message' => "Serviço não encontrado."]);
        }

        $servicoRequest = new ServicoRequest();
        $validator =  \Validator::make(request()->all(), $servicoRequest->rules(), $servicoRequest->messages());
        if ($validator->fails()) {
            Session::flash('message', ['type' => 'danger', 'message' => $validator->messages()->first()]);
        } else {
            $this->repository->destroy($servico);
        }

    }
}

resources/views/servicos/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">

    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-sm-4 col-md-4 col-xl-4 text-left">
                            <h3 style="margin-bottom:10px"> Serviço </h3>
                        </div>
                    </div>

                    @component('components.form', ['action'=>route('servicos.store'), 'method'=>'POST'])
                    <div class="form-group row offset-1">
                        <div class="col-sm-5">
                            @include('components.inputs', ['name' => 'nome', 'type' => 'text'])
                        </div>
                        <div class="col-sm-5">
                            @include('components.inputs', ['name' => 'preco', 'type' => 'text', 'label' => 'Preço'])
                        </div>
                        <div class="col-sm-5">
                            @include('components.inputs', ['name' => 'tempo_estimado', 'type' => 'text', 'label' => 'Tempo estimado'])
                        </div>
                        <div class='col-sm-5'>
                            @include('components.inputs', ['name' => 'unidade_tempo', 'type' => 'select', 'label' => 'Unidade tempo', 'value'=>null, 'optionKey'=>'id', 'optionValue'=>'nome', 'options'=>$unidades_tempo])
                        </div>
                        <div class="col-sm-5">
                            @include('components.inputs', ['name' => 'pontos_ganhos', 'type' => 'text', 'label' => 'Pontos ganhos'])
                        </div>
                        <div class="col-sm-5">
                            @include('components.inputs', ['name' => 'pontos_necessarios', 'type' => 'text', 'label' => 'Pontos necessários'])
                        </div>
                        <div class='col-sm-5'>
                            @include('components.inputs', ['name' => 'atendido_por', 'type' => 'select', 'label' => 'Atendido por', 'value'=>null, 'optionKey'=>'id', 'optionValue'=>'nome', 'options'=>$perfis])
                        </div>
                        <div class='col-sm-5'>
                            @include('components.inputs', ['name' => 'ativo', 'type' => 'checkbox', 'value'=>1])
                        </div>
                        <div class='col-sm-10 text-right' style="margin-top: 10px;">
                            @include('components.buttons', ['type'=>'cancel', 'value'=>'Cancelar'] )
                            @include('components.inputs', ['type'=>'submit', 'id'=>'submit', 'value'=>'Salvar'] )
                        </div>
                    </div>
                    @endcomponent
                </div>
            </div>
        </div>
    </div>
</div>


@endsection

resources/views/servicos/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">

    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-sm-4 col-md-4 col-xl-4 text-left">
                            <h3 style="margin-bottom:10px"> Serviço </h3> Edição
                        </div>
                    </div>

                    @component('components.form', ['action'=>route('servicos.update', $servico->id), 'method'=>'PUT'])
                    <div class="form-group row offset-1">
                        <div class="col-sm-5">
                            @include('components.inputs', ['name' => 'nome', 'type' => 'text', 'value'=>$servico->produtoServico->nome])
                        </div>
                        <div class="col-sm-5">
                            @include('components.inputs', ['name' => 'preco', 'type' => 'text', 'label' => 'Preço', 'value'=>$servico->preco])
                        </div>
                        <div class="col-sm-5">
                            @include('components.inputs', ['name' => 'tempo_estimado', 'type' => 'text', 'label' => 'Tempo estimado', 'value'=>$servico->tempo_estimado])
                        </div>
                        <div class='col-sm-5'>
                            @include('components.inputs', ['name' => 'unidade_tempo', 'type' => 'select', 'label' => 'Unidade tempo', 'value'=>$servico->id_unidade_tempo, 'optionKey'=>'id', 'optionValue'=>'nome', 'options'=>$unidades_tempo])
                        </div>
                        <div class="col-sm-5">
                            @include('components.inputs', ['name' => 'pontos_ganhos', 'type' => 'text', 'label' => 'Pontos ganhos', 'value'=>$servico->pontos_ganhos])
                        </div>
                        <div class="col-sm-5">
                            @include('components.inputs', ['name' => 'pontos_necessarios', 'type' => 'text', 'label' => 'Pontos necessários', 'value'=>$servico->pontos_necessarios])
                        </div>
                        <div class='col-sm-5'>
                            @include('components.inputs', ['name' => 'atendido_por', 'type' => 'select', 'label' => 'Atendido por', 'value'=>$servico->id_perfil, 'optionKey'=>'id', 'optionValue'=>'nome', 'options'=>$perfis])
                        </div>
                        <div class='col-sm-5'>
                            @include('components.inputs', ['name' => 'ativo', 'type' => 'checkbox', 'value'=>$servico->produtoServico->ativo])
                        </div>
                        <div class='col-sm-10 text-right' style="margin-top: 10px;">
                            @include('components.buttons', ['type'=>'cancel', 'value'=>'Cancelar'] )
                            @include('components.inputs', ['type'=>'submit', 'id'=>'submit', 'value'=>'Salvar'] )
                        </div>
                    </div>
                    @endcomponent
                </div>
            </div>
        </div>
    </div>
</div>


@endsection

resources/views/servicos/index.blade.php
@extends('layouts.app')

@section('content')


<div class="container">

    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-sm-4 col-md-4 col-xl-4 text-left">
                            <h3 style="margin-bottom:10px"> Serviços </h3>
                        </div>
                        <div class="col-sm-8 col-md-8 col-xl-8 text-right">
                            <a class="btn btn-warning" id="pesquisar" name="pesquisar" href="javascript:jQuery('#filter').toggle('1000')" role="button">Pesquisar</a>
                            <a class="btn btn-primary" id="novo" name="novo" href="{{route('servicos.create')}}" role="button">Novo</a>
                        </div>
                    </div> 

                    <div id="filter" class="card" style="margin-top:20px; display:none">
                        <div class="card-body">
                            @component('components.form', ['action'=>route('servicos.index'), 'method'=>'GET'])
                            <div class="form-group row">
                                <div class="col-sm-3">
                                    @include('components.inputs', ['name' => 'nome', 'type' => 'text', 'inputClass'=>'form-control-sm', 'value'=>request()->get('nome') ])
                                </div>
                                <div class='col-xs-12 col-md-12 text-right' style="margin-top: 10px;">
                                    @include('components.inputs', ['type'=>'submit', 'value'=>'Filtrar', 'name'=>'filtrar', 'inputClass'=>'btn-sm'] )
                                </div>
                            @endcomponent
                            </div>
                        </div>
                    </div>

                    @if(Session::has('message'))
                    @include('components.alerts', ['data'=>Session::get('message')])
                    @endif
                    @if($servicos->count() > 0)
                    <div class="table-responsive" style="margin-top:20px">
                        <table class="table table-hover table-striped table-sm">
                            <thead>
                                <tr class="table-primary">
                                    <th scope="col">ID</th>
                                    <th scope="col">Nome</th>
                                    <th scope="col">Tempo estimado</th>
                                    <th scope="col">Preço</th>
                                    <th scope="col">Opções</th>
                                </tr>
                            </thead>
                            <tbody>

                                @foreach ($servicos as $servico)
                                <tr>
                                    <th scope="row">{{$servico->id}}</th>
                                    <td>{{$servico->nome}}</td>
                                    <td>{{$servico->tempo_estimado}} {{$servico->unidadeTempo->sigla}}</td>
                                    <td>R$ {{$servico->preco}}</td>
                                    <td> 
                                        @include('components.buttons', ['type'=>'edit', 'href'=>route('servicos.edit', $servico->id)]) </a>
                                        @include('components.buttons', ['type'=>'delete', 'href'=>route('servicos.destroy', $servico->id), 'id'=>$servico->id, 'message'=>'Deseja excluir o serviço "'. $servico->produtoServico->nome.'"?']) 
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>

                        <div class='col-xs-12 col-md-12 text-center'>
                            {{ $servicos->links() }}
                        </div>

                        <footer class="blockquote-footer"> Total: {{$servicos->total() > 1 ? $servicos->total() . ' registros encontrados.' : '1 registro encontrado.' }} </footer>
                    </div>
                    @else
                    <div class="alert alert-warning" role="alert" style="margin-top:20px">
                        Nenhum registro encontrado
                    </div>
                    @endif
                </div>
            </div>
        </div>
    </div>
</div>
@endsection