routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['register'=>false, 'reset'=>false]);

Route::group(['middleware' => ['auth']], function () {
    Route::resource('/agendamentos', 'AgendamentoController');
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('/pets', 'PetController');
    Route::resource('/servicos', 'ServicoController');
    
    Route::prefix('relatorios')->group(function(){
        Route::get('/avaliacoes', 'RelatorioAvaliacoesController@index')->name('relatorio_avaliacoes');
    });
    
    
});

app/Models/Agendamento.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Agendamento extends Model
{
    protected $table = 'agendamentos';

    protected $fillable = [
        'id_pet'
    ];

    protected $with = ['servicos', 'pet'];

    public function servicos()
    {
        return $this->hasMany('App\Models\AgendamentoServico', 'id_agendamento', 'id');
    }

    public function scopeComData($query, $data)
    {
        return $query->whereHas('servicos', function($q) use ($data) {
            $q->whereDate('data_inicio', $data);
        });
    }

    public function pet()
    {
        return $this->belongsTo('App\Models\Pet', 'id_pet', 'id');
    }

}

app/Http/Controllers/AgendamentoController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\AgendamentoRequest;
use App\Models\Agendamento;
use App\Repositories\AgendamentoRepository;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;

class AgendamentoController extends Controller
{


    public function __construct()
    {
        $this->repository = new AgendamentoRepository();
    }

    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        try {
            $this->authorize('viewAny', Agendamento::class);
            return $this->repository->index($request);
        } catch (\Exception $e) {
            Session::flash('message', ['type' => 'danger', 'message' => "Permissão negada"]);
            return redirect()->back();
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        try {
            $this->authorize('create', Agendamento::class);
            return $this->repository->create();
        } catch (\Exception $e) {
            dd($e);
            Session::flash('message', ['type' => 'danger', 'message' => "Permissão negada"]);
            return redirect()->back();
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(AgendamentoRequest $request)
    {
        try {
            $this->authorize('create', Agendamento::class);
            $this->repository->store($request);
            return redirect()->route('agendamentos.index');
        } catch (\Exception $e) {
            dd($e);
            Session::flash('message', ['type' => 'danger', 'message' => "Permissão negada"]);
            return redirect()->back();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        
        try {
            $this->authorize('view', [Agendamento::find($id), request()->user()]);
        } catch (\Exception $e) {
            Session::flash('message', ['type' => 'danger', 'message' => "Permissão negada"]);
            return redirect()->back();
        }

        try {
            $agendamento = Agendamento::findOrFail($id);
        } catch (ModelNotFoundException $e) {
            Session::flash('message', ['type' => 'danger', 'message' => "Serviço não encontrado."]);
            return redirect()->back();
        }
        
        return $this->repository->edit($agendamento);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(AgendamentoRequest $request, $id)
    {
        try {
            $this->authorize('update', [Agendamento::find($id), $request->user()]);
        } catch (\Exception $e) {
            Session::flash('message', ['type' => 'danger', 'message' => "Permissão negada"]);
            return redirect()->back();
        }

        try {
            $agendamento = Agendamento::findOrFail($id);
        } catch (\Exception $e) {
            Session::flash('message', ['type' => 'danger', 'message' => "Agendamento não encontrado."]);
            return redirect()->back()->withInput();
        }

        $this->repository->update($request, $agendamento);
        return redirect()->route('agendamentos.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            $this->authorize('delete', [Agendamento::find($id), request()->user()]);
        } catch (\Exception $e) {
            Session::flash('message', ['type' => 'danger', 'message' => "Permissão negada"]);
        }

        try {
            $agendamento = Agendamento::findOrFail($id);
        } catch (\Exception $e) {
            Session::flash('message', ['type' => 'danger', 'message' => "Agendamento não encontrado."]);
        }

        $agendamentoRequest = new AgendamentoRequest();
        $validator =  \Validator::make(['id'=>$id], $agendamentoRequest->rules(), $agendamentoRequest->messages());
        if ($validator->fails()) {
            Session::flash('message', ['type' => 'danger', 'message' => $validator->messages()->first()]);
        } else {
            $this->repository->destroy($agendamento);
        }
        
    }
}

resources/views/agendamentos/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">

    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-sm-4 col-md-4 col-xl-4 text-left">
                            <h3 style="margin-bottom:10px"> Agendamento </h3>
                        </div>
                    </div>

                    @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                    @endif

                    <span id="grupo-servico" class="form-group row col-sm-12" style="display:none">
                        <div class='col-sm-3'>
                            @include('components.inputs', ['id'=>'servico', 'name'=>'servico[]', 'label'=>'Serviço', 'type'=>'select', 'value'=>null, 'optionKey'=>'id', 'optionValue'=>'nome', 'options'=>$servicos])
                        </div>
                        <div class='col-sm-3'>
                            @include('components.inputs', ['id'=>'funcionario', 'name'=>'funcionario[]', 'label'=>'Funcionário', 'type'=>'select', 'value'=>null, 'optionKey'=>'id', 'optionValue'=>'nome', 'options'=>$funcionarios])
                        </div>
                        <div class="col-sm-2">
                            @include('components.inputs', ['id'=>'horario', 'name'=>'horario[]', 'label'=>'Horário', 'type'=>'time'])
                        </div>
                        <div class='col-sm-3'>
                            @include('components.inputs', ['id'=>'situacao', 'name'=>'situacao[]', 'label'=>'Situação', 'type'=>'select', 'value'=>null, 'optionKey'=>'id', 'optionValue'=>'nome', 'options'=>$situacoes])
                        </div>
                    </span>
                    @component('components.form', ['action'=>route('agendamentos.store'), 'method'=>'POST'])
                    <div class="form-group row col-sm-12 ">
                        <div class="col-sm-5">
                            @include('components.inputs', ['name'=>'data', 'type'=>'date', 'value'=>date('Y-m-d')])
                        </div>
                        <div class="col-sm-5">
                            @include('components.inputs', ['name'=>'pet', 'type'=>'select', 'label'=>'Pet', 'value'=>null, 'optionKey'=>'id', 'optionValue'=>'nome', 'options'=>$pets])
                        </div>
                        <div class="col-sm-1">
                            <div class="form-group">
                                <a id="incluir" name="incluir" class="btn btn-primary btn-sm form-control" href="#" onclick="incluir()"> <i class="fas fa-plus"> </i> </a>
                            </div>
                        </div>

                        <div id='servicos' class="form-group row col-sm-12">

                        </div>

                        <div class='col-sm-12 text-right' style="margin-top: 10px;">
                            @include('components.buttons', ['type'=>'cancel', 'value'=>'Cancelar'] )
                            @include('components.inputs', ['type'=>'submit', 'id'=>'submit', 'value'=>'Salvar'] )
                        </div>

                    </div>
                    <script type="text/javascript">
                        window.onload = () => {
                            incluir()
                        }

                        incluir = () => {

                            let a = document.createElement('a')
                            a.classList.add('btn', 'btn-danger', 'btn-sm', 'form-control')
                            a.onclick = (e) => {
                                if (confirm('Deseja remover o serviço?')) {
                                    e.path[0].closest("#grupo-servico").remove()
                                }
                            }
                            a.href = '#'
                            a.innerHTML = '<i class="fa fa-trash" aria-hidden="true"> </i>';

                            let divfg = document.createElement('div')
                            divfg.classList.add('form-group')
                            divfg.appendChild(a)

                            let div = document.createElement('div')
                            div.classList.add('col-sm-1')
                            div.appendChild(divfg)

                            let grupoServico = document.querySelector('#grupo-servico').cloneNode(true)
                            grupoServico.style.display = '';
                            grupoServico.appendChild(div)

                            document.querySelector('#servicos')
                                .appendChild(grupoServico);
                        }
                    </script>
                    @endcomponent
                </div>
            </div>
        </div>
    </div>
</div>


@endsection

resources/views/agendamentos/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">

    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-sm-4 col-md-4 col-xl-4 text-left">
                            <h3 style="margin-bottom:10px"> Agendamento </h3>
                        </div>
                    </div>

                    @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                    @endif

                    <span id="grupo-servico" class="row col-sm-11" style="display:none">
                        <div class='col-sm-4'>
                            @include('components.inputs', ['id'=>'servico', 'name'=>'servico[]', 'label'=>'Serviço', 'type'=>'select', 'value'=>null, 'optionKey'=>'id', 'optionValue'=>'nome', 'options'=>$servicos])
                        </div>
                        <div class='col-sm-4'>
                            @include('components.inputs', ['id'=>'funcionario', 'name'=>'funcionario[]', 'label'=>'Funcionário', 'type'=>'select', 'value'=>null, 'optionKey'=>'id', 'optionValue'=>'nome', 'options'=>$funcionarios])
                        </div>
                        <div class="col-sm-3">
                            @include('components.inputs', ['id'=>'horario', 'name'=>'horario[]', 'label'=>'Horário', 'type'=>'time'])
                        </div>
                    </span>
                    @component('components.form', ['action'=>route('agendamentos.update',$agendamento->id), 'method'=>'PUT'])
                    <div class="form-group row col-sm-12">
                        <div class="col-sm-5">
                            
                            @include('components.inputs', ['name'=>'data', 'type'=>'date', 'value'=>$agendamento->servicos->get(0)->data_inicio->format('Y-m-d')])
                        </div>
                        <div class="col-sm-5">
                            @include('components.inputs', ['name'=>'pet', 'type'=>'select', 'label'=>'Pet', 'value'=>$agendamento->id_pet, 'optionKey'=>'id', 'optionValue'=>'nome', 'options'=>$pets])
                        </div>
                        <div class="col-sm-1">
                            <div class="form-group">
                                <a id="incluir" name="incluir" class="btn btn-primary btn-sm form-control" href="#" onclick="incluir()"> <i class="fas fa-plus"> </i> </a>
                            </div>
                        </div>

                        @foreach($agendamento->servicos as $agendamentoServico)
                        <span id="grupo-servico" class="form-group row col-sm-12">
                        <div class='col-sm-3'>
                            @include('components.inputs', ['id'=>'servico', 'name'=>'servico[]', 'label'=>'Serviço', 'type'=>'select', 'value'=>$agendamentoServico->id_servico, 'optionKey'=>'id', 'optionValue'=>'nome', 'options'=>$servicos])
                        </div>
                        <div class='col-sm-3'>
                            @include('components.inputs', ['id'=>'funcionario', 'name'=>'funcionario[]', 'label'=>'Funcionário', 'type'=>'select', 'value'=>$agendamentoServico->id_pessoa, 'optionKey'=>'id', 'optionValue'=>'nome', 'options'=>$funcionarios])
                        </div>
                        <div class="col-sm-2">
                            @include('components.inputs', ['id'=>'horario', 'name'=>'horario[]', 'label'=>'Horário', 'type'=>'time', 'value'=>$agendamentoServico->data_inicio->format('H:i')])
                        </div>
                        <div class='col-sm-3'>
                            @include('components.inputs', ['id'=>'situacao', 'name'=>'situacao[]', 'label'=>'Situação', 'type'=>'select', 'value'=>$agendamentoServico->id_agendamento_situacao, 'optionKey'=>'id', 'optionValue'=>'nome', 'options'=>$situacoes])
                        </div>
                        <div class="col-sm-1">
                            <div class="form-group">
                                <a id="excluir" class="btn btn-danger btn-sm form-control" href="#" onclick="excluir(this)"> <i class="fas fa-trash"> </i> </a>
                            </div>
                        </div>
                        
                        </span>

                        @endforeach

                        <div id='servicos' class="form-group row col-sm-12">

                        </div>

                        <div class='col-sm-12 text-right' style="margin-top: 10px;">
                            @include('components.buttons', ['type'=>'cancel', 'value'=>'Cancelar'] )
                            @include('components.inputs', ['type'=>'submit', 'id'=>'submit', 'value'=>'Salvar'] )
                        </div>

                    </div>
                    <script type="text/javascript">

                        incluir = () => {
                            
                            let a = document.createElement('a')
                            a.classList.add('btn', 'btn-danger', 'btn-sm', 'form-control')
                            a.onclick = (e) => {
                                if (confirm('Deseja remover o serviço?')) {
                                    e.path[0].closest("#grupo-servico").remove()
                                }
                            }
                            a.innerHTML = '<i class="fas fa-trash"> </i>';
                            a.href = '#';

                            let divfg = document.createElement('div')
                            divfg.classList.add('form-group')
                            divfg.appendChild(a)

                            let div = document.createElement('div')
                            div.classList.add('col-sm-1')
                            div.appendChild(divfg)

                            let grupoServico = document.querySelector('#grupo-servico').cloneNode(true)
                            grupoServico.style.display = '';
                            grupoServico.appendChild(div)

                            document.querySelector('#servicos')
                                .appendChild(grupoServico);
                        }
                        
                        excluir = (e) => {
                            if (confirm('Deseja remover o serviço?')) {
                                e.closest("#grupo-servico").remove()
                            }
                        }
                    </script>
                    @endcomponent
                </div>
            </div>
        </div>
    </div>
</div>


@endsection

resources/views/agendamentos/index.blade.php
@extends('layouts.app')

@section('content')


<div class="container">

    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-sm-4 col-md-4 col-xl-4 text-left">
                            <h3 style="margin-bottom:10px"> Agendamentos </h3>
                        </div>
                        <div class="col-sm-8 col-md-8 col-xl-8 text-right">                        
                            <a class="btn btn-warning" id="pesquisar" name="pesquisar" href="javascript:jQuery('#filter').toggle('1000')" role="button">Pesquisar</a>
                            <a class="btn btn-primary" id="novo" name="novo" href="{{route('agendamentos.create')}}" role="button">Novo</a>
                        </div>
                    </div>

                    <div id="filter" class="card" style="margin-top:20px;">
                        <div class="card-body">
                            @component('components.form', ['action'=>route('agendamentos.index'), 'method'=>'GET'])
                            <div class="form-group row">
                                <div class="col-sm-3">
                                    @include('components.inputs', ['name' => 'data', 'type' => 'date', 'inputClass'=>'form-control-sm', 'value'=>request()->get('data') ? request()->get('data') : date('Y-m-d') ])
                                </div>

                                <div class='col-xs-12 col-md-12 text-right' style="margin-top: 10px;">
                                    @include('components.inputs', ['type'=>'submit', 'value'=>'Filtrar', 'name'=>'filtrar' ,'inputClass'=>'btn-sm'] )
                                </div>
                            @endcomponent
                            </div>
                        </div>
                    </div>

                    @if(Session::has('message'))
                    @include('components.alerts', ['data'=>Session::get('message')])
                    @endif
                    @if($agendamentos->count() > 0)
                    <div class="table-responsive" style="margin-top:20px">
                        <table class="table table-hover table-striped table-sm">
                            <thead>
                                <tr class="table-primary">
                                    <th scope="col">ID</th>
                                    <th scope="col">Pet</th>
                                    <th scope="col">Tipo</th>
                                    <th scope="col">Cliente</th>
                                    <th scope="col">Serviços</th>
                                    <th scope="col">Opções</th>
                                </tr>
                            </thead>
                            <tbody>

                                @foreach ($agendamentos as $agendamento)
                                <tr>
                                    <th scope="row">{{$agendamento->id}}</th>
                                    <td>{{$agendamento->pet->nome}}</td>
                                    <td>{{$agendamento->pet->tipo->nome}}</td>
                                    <td>{{$agendamento->pet->dono->nome}}</td>
                                    <td> 
                                        @foreach ($agendamento->servicos as $servico) 
                                        {{$servico->produtoServico->nome}} &bull; {{$servico->horario}} &bull; {{$servico->veterinario->nome}}<br/>
                                        @endforeach
                                    </td>
                                    <td> 
                                        @include('components.buttons', ['type'=>'edit', 'href'=>route('agendamentos.edit', $agendamento->id)]) </a>
                                        @include('components.buttons', ['type'=>'delete', 'href'=>route('agendamentos.destroy', $agendamento->id), 'id'=>$agendamento->id, 'message'=>'Deseja excluir o agendamento "'. $agendamento->id.'"?']) 
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>

                        <div class='col-xs-12 col-md-12 text-center'>
                            {{ $agendamentos->links() }}
                        </div>

                        <footer class="blockquote-footer"> Total: {{$agendamentos->total() > 1 ? $agendamentos->total() . ' registros encontrados.' : '1 registro encontrado.' }} </footer>
                    </div>
                    @else
                    <div class="alert alert-warning" role="alert" style="margin-top:20px">
                        Nenhum registro encontrado
                    </div>
                    @endif
                </div>
            </div>
        </div>
    </div>
</div>
@endsection