routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['register'=>false, 'reset'=>false]);

Route::group(['middleware' => ['auth']], function () {
    Route::resource('/agendamentos', 'AgendamentoController');
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('/pets', 'PetController');
    Route::resource('/servicos', 'ServicoController');
    
    Route::prefix('relatorios')->group(function(){
        Route::get('/avaliacoes', 'RelatorioAvaliacoesController@index')->name('relatorio_avaliacoes');
    });
    
    
});

app/Models/Pet.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Pet extends Model
{
    protected $table = 'pets';

    protected $fillable = [
        'id_pessoa',
        'id_tipo_pet',
        'nome',
        'porte',
        'observacoes',
        'permite_foto',
        'ativo',
    ];

    protected $with = ['dono', 'tipo'];

    public function dono()
    {
        return $this->belongsTo('App\Models\Pessoa', 'id_pessoa', 'id');
    }

    public function tipo()
    {
        return $this->belongsTo('App\Models\TipoPet', 'id_tipo_pet', 'id');
    }

    public function scopeComNome($query, $nome)
    {
        return $query->where('nome', 'like' ,"%$nome%");
    }

    public function scopeAtivo($query, $ativo)
    {
        return $query->where('ativo', $ativo);
    }

}

app/Http/Controllers/PetController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\PetRequest;
use App\Models\Pet;
use App\Repositories\PetRepository;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;

class PetController extends Controller
{


    public function __construct()
    {
        $this->repository = new PetRepository();
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        try {
            $this->authorize('viewAny', Pet::class);
            return $this->repository->index($request);
        } catch (\Exception $e) {
            Session::flash('message', ['type' => 'danger', 'message' => "Permissão negada"]);
            return redirect()->back();
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        try {
            $this->authorize('create', Pet::class);
            return $this->repository->create();
        } catch (\Exception $e) {
            Session::flash('message', ['type' => 'danger', 'message' => "Permissão negada"]);
            return redirect()->back();
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(PetRequest $request)
    {
        try {
            $this->authorize('create', Pet::class);
            $this->repository->store($request);
            return redirect()->route('pets.index');
        } catch (\Exception $e) {
            Session::flash('message', ['type' => 'danger', 'message' => "Permissão negada"]);
            return redirect()->back();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

        /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        try {
            $this->authorize('view', [Pet::find($id), request()->user()]);
        } catch (\Exception $e) {
            Session::flash('message', ['type' => 'danger', 'message' => "Permissão negada"]);
            return redirect()->back();
        }

        try {
            $pet = Pet::findOrFail($id);
        } catch (ModelNotFoundException $e) {
            Session::flash('message', ['type' => 'danger', 'message' => "Serviço não encontrado."]);
            return redirect()->back();
        }
        return $this->repository->edit($pet);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(PetRequest $request, $id)
    {
        try {
            $this->authorize('update', [Pet::find($id), $request->user()]);
        } catch (\Exception $e) {
            Session::flash('message', ['type' => 'danger', 'message' => "Permissão negada"]);
            return redirect()->back();
        }

        try {
            $pet = Pet::findOrFail($id);
        } catch (\Exception $e) {
            Session::flash('message', ['type' => 'danger', 'message' => "Serviço não encontrado."]);
            return redirect()->back();
        }

        $this->repository->update($request, $pet);
        return redirect()->route('pets.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            $this->authorize('delete', [Pet::find($id), request()->user()]);
        } catch (\Exception $e) {
            Session::flash('message', ['type' => 'danger', 'message' => "Permissão negada"]);
        }

        try {
            $pet = Pet::findOrFail($id);
        } catch (\Exception $e) {
            Session::flash('message', ['type' => 'danger', 'message' => "Pet não encontrado."]);
        }

        $petRequest = new PetRequest();
        $validator =  \Validator::make(request()->all(), $petRequest->rules(), $petRequest->messages());
        if ($validator->fails()) {
            Session::flash('message', ['type' => 'danger', 'message' => $validator->messages()->first()]);
        } else {
            $this->repository->destroy($pet);
        }

    }
}

resources/views/pets/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">

    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-sm-4 col-md-4 col-xl-4 text-left">
                            <h3 style="margin-bottom:10px"> Pet </h3>
                        </div>
                    </div>

                    @component('components.form', ['action'=>route('pets.store'), 'method'=>'POST'])
                    <div class="form-group row offset-1">
                        <div class="col-sm-5">
                            @include('components.inputs', ['name'=>'nome', 'type'=>'text'])
                        </div>
                        <div class="col-sm-5">
                        @include('components.inputs', ['name'=>'tipo_pet', 'type'=>'select', 'label'=>'Tipo pet', 'value'=>null, 'optionKey'=>'id', 'optionValue'=>'nome', 'options'=>$tipos])
                        </div>
                        <div class="col-sm-5">
                            @include('components.inputs', ['name'=>'porte', 'type'=>'text'])
                        </div>
                        <div class='col-sm-5'>
                            @include('components.inputs', ['name'=>'cliente', 'type'=>'select', 'value'=>null, 'optionKey'=>'id', 'optionValue'=>'nome', 'options'=>$clientes])
                        </div>
                        <div class="col-sm-10">
                            @include('components.inputs', ['name'=>'observacoes', 'label'=>'Observações', 'type'=>'textArea'])
                        </div>
                        <div class='col-sm-5'>
                            @include('components.inputs', ['name'=>'permite_foto', 'label'=>'Permite foto', 'type'=>'checkbox', 'value'=>1])
                        </div>
                        <div class='col-sm-5'>
                            @include('components.inputs', ['name'=>'ativo', 'type'=>'checkbox', 'value'=>1])
                        </div>
                        <div class='col-sm-10 text-right' style="margin-top: 10px;">
                            @include('components.buttons', ['type'=>'cancel', 'value'=>'Cancelar'] )
                            @include('components.inputs', ['type'=>'submit', 'id'=>'submit', 'value'=>'Salvar'] )
                        </div>
                    </div>
                    @endcomponent
                </div>
            </div>
        </div>
    </div>
</div>


@endsection

resources/views/pets/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">

    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-sm-4 col-md-4 col-xl-4 text-left">
                            <h3 style="margin-bottom:10px"> Pet </h3>
                        </div>
                    </div>

                    @component('components.form', ['action'=>route('pets.update', $pet->id), 'method'=>'PUT'])
                    <div class="form-group row offset-1">
                        <div class="col-sm-5">
                            @include('components.inputs', ['name'=>'nome', 'type'=>'text', 'value'=>$pet->nome])
                        </div>
                        <div class="col-sm-5">
                        @include('components.inputs', ['name'=>'tipo_pet', 'type'=>'select', 'label'=>'Tipo pet', 'value'=>$pet->id_tipo_pet, 'optionKey'=>'id', 'optionValue'=>'nome', 'options'=>$tipos])
                        </div>
                        <div class="col-sm-5">
                            @include('components.inputs', ['name'=>'porte', 'type'=>'text', 'value'=>$pet->porte])
                        </div>
                        <div class='col-sm-5'>
                            @include('components.inputs', ['name'=>'cliente', 'type'=>'select', 'value'=>$pet->id_pessoa, 'optionKey'=>'id', 'optionValue'=>'nome', 'options'=>$clientes])
                        </div>
                        <div class="col-sm-10">
                            @include('components.inputs', ['name'=>'observacoes', 'label'=>'Observações', 'type'=>'textArea', 'value'=>$pet->observacoes])
                        </div>
                        <div class='col-sm-5'>
                            @include('components.inputs', ['name'=>'permite_foto', 'label'=>'Permite foto', 'type'=>'checkbox', 'value'=>$pet->permite_foto])
                        </div>
                        <div class='col-sm-5'>
                            @include('components.inputs', ['name'=>'ativo', 'type'=>'checkbox', 'value'=>$pet->ativo])
                        </div>
                        <div class='col-sm-10 text-right' style="margin-top: 10px;">
                            @include('components.buttons', ['type'=>'cancel', 'value'=>'Cancelar'] )
                            @include('components.inputs', ['type'=>'submit', 'id'=>'submit', 'value'=>'Salvar'] )
                        </div>
                    </div>
                    @endcomponent
                </div>
            </div>
        </div>
    </div>
</div>


@endsection

resources/views/pets/index.blade.php
@extends('layouts.app')

@section('content')


<div class="container">

    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-sm-4 col-md-4 col-xl-4 text-left">
                            <h3 style="margin-bottom:10px"> Pets </h3>
                        </div>
                        <div class="col-sm-8 col-md-8 col-xl-8 text-right">
                            <a class="btn btn-warning" id="pesquisar" name="pesquisar" href="javascript:jQuery('#filter').toggle('1000')" role="button">Pesquisar</a>
                            <a class="btn btn-primary" id="novo" name="novo" href="{{route('pets.create')}}" role="button">Novo</a>
                        </div>
                    </div>

                    <div id="filter" class="card" style="margin-top:20px; display:none">
                        <div class="card-body">
                            @component('components.form', ['action'=>route('pets.index'), 'method'=>'GET'])
                            <div class="form-group row">
                                <div class="col-sm-3">
                                    @include('components.inputs', ['name' => 'nome', 'type' => 'text', 'inputClass'=>'form-control-sm', 'value'=>request()->get('nome') ])
                                </div>
                                <div class='col-xs-12 col-md-12 text-right' style="margin-top: 10px;">
                                    @include('components.inputs', ['type'=>'submit', 'value'=>'Filtrar', 'name'=>'filtrar', 'inputClass'=>'btn-sm'] )
                                </div>
                            @endcomponent
                            </div>
                        </div>
                    </div>

                    @if(Session::has('message'))
                    @include('components.alerts', ['data'=>Session::get('message')])
                    @endif
                    @if($pets->count() > 0)
                    <div class="table-responsive" style="margin-top:20px">
                        <table class="table table-hover table-striped table-sm">
                            <thead>
                                <tr class="table-primary">
                                    <th scope="col">ID</th>
                                    <th scope="col">Nome</th>
                                    <th scope="col">Tipo</th>
                                    <th scope="col">Cliente</th>
                                    <th scope="col">Opções</th>
                                </tr>
                            </thead>
                            <tbody>

                                @foreach ($pets as $pet)
                                <tr>
                                    <th scope="row">{{$pet->id}}</th>
                                    <td>{{$pet->nome}}</td>
                                    <td>{{$pet->tipo->nome}}</td>
                                    <td>{{$pet->dono->nome}}</td>
                                    <td> 
                                        @include('components.buttons', ['type'=>'edit', 'href'=>route('pets.edit', $pet->id)]) </a>
                                        @include('components.buttons', ['type'=>'delete', 'href'=>route('pets.destroy', $pet->id), 'id'=>$pet->id, 'message'=>'Deseja excluir o pet "'. $pet->nome.'"?']) 
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>

                        <div class='col-xs-12 col-md-12 text-center'>
                            {{ $pets->links() }}
                        </div>

                        <footer class="blockquote-footer"> Total: {{$pets->total() > 1 ? $pets->total() . ' registros encontrados.' : '1 registro encontrado.' }} </footer>
                    </div>
                    @else
                    <div class="alert alert-warning" role="alert" style="margin-top:20px">
                        Nenhum registro encontrado
                    </div>
                    @endif
                </div>
            </div>
        </div>
    </div>
</div>
@endsection